kind: Service
apiVersion: v1
metadata:
  labels:
    squad: frontend
  name: hey-service
  namespace: default
spec:
  selector:
    app: hey
  type: ClusterIP
  ports:
  - name: hey-port
    protocol: TCP
    port: 8000
    targetPort: hey-port 
